[package]
name = "dylan/orthogonalframeworkv2"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Signal = "sleitnick/signal@2.0.1"
Promise = "evaera/promise@4.0.0"
Net = "sleitnick/net@0.2.0"
Janitor = "howmanysmall/janitor@1.16.0"
PartCache = "4igz/partcache@1.0.1"

Stew = "data-oriented-house/stew@5.6.0"
Sandwich = "data-oriented-house/sandwich@2.2.1"
Squash = "data-oriented-house/squash@2.2.0"
TableValue = "data-oriented-house/tablevalue@3.0.0"
# TopbarPlus = "1foreverhd/topbarplus@3.0.2"
TopbarPlus = "legitatx/topbarplus@3.0.5"
Fusion = "mattschrubb/fusion@1.2.5"
# Fusion = "elttob/fusion@0.2.0"

[server-dependencies]
Cmdr = "evaera/cmdr@1.12.0"
ProfileService = "surnautica/profileservice@1.0.0"
